public AddColors() {
    CAddColor("matRed",     0xF44336);  // Red Team Color
    CAddColor("matBlue",    0x2196F3);  // Blue Team Color
    CAddColor("matPurple",  0x9C27B0);  // Warning Color
    CAddColor("matGreen",   0x4CAF50);  // Success Color
    CAddColor("matLGreen",  0x8BC34A);  // Success Color
    CAddColor("matCyan",    0x00BCD4);  // Info Color
    CAddColor("matAmber",   0xFFC107);  // Tag Color
    CAddColor("matOrange",  0xFF9800);  // Error Color
    CAddColor("matDOrange", 0xFF5722);  // Error Color
    CAddColor("matYellow",  0xFFEB3B);  // List Color
    CAddColor("matWhite",   0xFAFAFA);  // White Color
}