// Core Includes
#include <sourcemod>
#include <sdkhooks>
#include <morecolors>
#include <tf2>
#include <tf2_stocks>
#include <match>

// Module Includes
#include <roll>
#include <fight>
#include <pick>

// Utils Includes
#include <hud>
#include <player>
#include <cvars>
#include <utils>

// Admin Module Includes
#include <admin/markplusone>

// Mode Module Includes
#include <mode/spec-roll>
#include <mode/captain>

// Fight Module Includes
#include <fight/melee>

// Pick Module Includes
#include <pick/playermenu>

#undef REQUIRE_PLUGIN
#include <updater>